- hosts: webservers
  become: yes
  vars:
    http_port: 8000
    https_port: 4443
    html_welcome_message: "Hello There! How are you?"

  tasks:
    - include_tasks: tasks/apache2_install.yml

  handlers:
    - include_tasks: handlers/main.yml