- name: "Deploy nginx sites configuration"
  template: src=mysite.j2 dest="/etc/nginx/sites-enabled/mysite"
  notify: restart nginx
  tags: configuration # task level tag

- name: "Remove defaults"
  # Ansible will make sure that this file is deleted. it deletes it, if it exists
  file: path="/etc/nginx/sites-enabled/default" state=absent
  tags: configuration # task level tag
   